### ISSUE TITLE
error after updating to babel@6

### ISSUE THREAD

**Issue by Guria** [jscs-dev/babel-jscs#24]
```
node_modules/babel-jscs/acorn-to-esprima.js:2
var tt       = require("babel-core").acorn.tokTypes;
                                          ^

TypeError: Cannot read property 'tokTypes' of undefined
    at Object.<anonymous> (/home/guria/wspace/kg-grid/node_modules/babel-jscs/acorn-to-esprima.js:2:43)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/guria/wspace/kg-grid/node_modules/babel-jscs/index.js:1:84)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
```

**Comment by hzoo** [comment]
Yeah it's not going to work until we fix all of that. There is a lot of breaking changes so it may take a while.

**Comment by hzoo** [comment]
Also are you using babel-jscs standalone or are you using jscs with `--esnext` or `"esnext": true`? You shouldn't need to use babel-jscs by itself.

**Comment by tymondesigns** [comment]
Any update on Babel 6 compatibility?

**Comment by elicwhite** [comment]
We just ran into this problem as well while trying to update to Babel 6.

**Comment by hzoo** [comment]
It's still using babel 5 I need to update it later. Also it's weird since it's bundled with jscs - if I update to babel 6 I wonder if it will break users on babel 5. I could do a major version of babel-jscs and ask users to update that instead.

**Comment by hzoo** [comment]
Haven't tested much yet but I published `babel-jscs@3.0.0-beta1` (using babel 6) so you will have to install this separately (outside of jscs). Once its stable I can update it in jscs itself.

You will have to use `"esprima": "babel-jscs"` in your config instead of simply `"esnext": true` (uses the babel-jscs in jscs itself). (there is a known issue with getters/setters)

**Comment by jakemmarsh** [comment]
Since `jscs` specifies `"babel-jscs": "^2.0.0"`, it still installs its own version even if `babel-jscs@3.0.0-beta1` is installed. Replacing `"esnext": true` with `"esprima": "babel-jscs"` still doesn't seem to force it to use the beta version.

**Comment by hzoo** [comment]
Hmm weird. Just doing that worked for me. Maybe since I cleared my node_modules (also npm 3).

Maybe try `"esprima": "./node_modules/babel-jscs",` to use the higher level one instead of the jscs one.

**Comment by hzoo** [comment]
Is this still an issue?

**Comment by jakemmarsh** [comment]
I still wasn't able to get it to work with `"esprima": "./node_modules/babel-jscs"` either, even after a fresh node_modules install

**Comment by hzoo** [comment]
Hm are you using npm 2 or 3? It should work for 3

**Comment by elicwhite** [comment]
npm 2, node 0.12.7

**Comment by hzoo** [comment]
What is the error message now with the more explicit path? I don't think I want to change jscs itself to use the beta version since there is still some problems

**Comment by JoeMattie** [comment]
I just ran into this.  It turns out the problem was caused by babel@5.x.x still being installed globally.

running sudo npm install -g babel@6 should do it

**Comment by jakemmarsh** [comment]
That did the trick! Thanks @JoeMattie

**Comment by hzoo** [comment]
Ah ok good point! We are going to encourage people to install babel locally as well - will try to fix the docs for that on babel

**Comment by jakemmarsh** [comment]
@hzoo we've gotten all the separate libraries working together and using the new `babel-core` by ensuring the only version installed is 6.0+. However, `jscs` still specifies a dependency of `babel-core@5.6.15`. Once that is installed (which is necessary to be able to shrinkwrap dependencies), it regresses to the original `tokTypes` error

**Comment by hzoo** [comment]
@jakemmarsh I removed the dependency in 2.8.0 https://github.com/jscs-dev/node-jscs/pull/2027/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L63 so maybe that should work?

**Comment by STRML** [comment]
@hzoo It would, but `babel-jscs` still has it as a dependency.

**Comment by rosskevin** [comment]
This is causing big headaches for me.  Any 5.x babel-core in the dependency tree causes problems and this is the last one for me:

``` bash
+-- grunt-jscs@2.7.0
| `-- jscs@2.9.0
|   `-- babel-jscs@2.0.5
|     `-- babel-core@5.8.35 
```

@see https://github.com/alienfast/gulp-pipeline/issues/3

Is there any way I can force babel-jscs up to a 6.x compatible version?

**Comment by hzoo** [comment]
I can force jscs to use babel-jscs 6.x - i just wasn't ready to do so since I think there are broken things I haven't been able to fix yet

**Comment by rosskevin** [comment]
I'm good with a temporary option to see if it works, but I've got the problem in a grunt project and a gulp project that I've converted to 6.x, so I'll either have to stop using jscs until it is fixed or get a workaround in now.

**Comment by rosskevin** [comment]
Actually, I take that back, I actually **need** a workaround, because transitive dependencies cannot be factored out of dependent projects (that I'm not in control of).  I'll need to modify them in my local install or find some way to override them using the convoluted shrinkwrap override.

**Comment by elicwhite** [comment]
Agreed. This is an even bigger problem when using shrinkwrap

**Comment by blazkovicz** [comment]
Manual installing babel-jscs 3.0.0 and removing babel-jscs from jscs/node-modules solves the problem for now.

**Comment by hzoo** [comment]
JSCS 3.0 doesn't need to use babel-jscs anymore since CST uses babylon underneath, let me know if that works out.
